### ISSUE TITLE
Knp Paginator

### ISSUE THREAD

**Issue by anthomas63** [Th3Mouk/CMSStarter#2]
You must install Knp Paginator Bundle because it's very usefull for every project.

**Comment by Th3Mouk** [comment]
KnpPaginatorBundle will be installed by default if a default functionality of the CMS need him. The philosophy of Symfony2 is to just use dependence on the need. I keep the same with the CMS project, the focus is to provide a ready to clone solution for content administration. Nothing prevent you to install over the bundles of your whishes. But actually the page-block system don't need an another paginator. It's the same thing like e-commerce bundles, or blog bundles, this project don't need one by default, each user must be free to choose the configuration of the project and additionals bundles.
